sudo: required
services:
  - docker

before_install:
  - docker build -t mphbo/react-with-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true mphbo/react-with-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-with-docker"
  env: "Reactwithdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-080740215952"
  bucket_path: "react-with-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
